org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.1
neoforge_version=26.1.0.6-beta

minecraft_version_range=[26.1,)
neoforge_version_range=[26.1.0-beta,)


## Mod Properties
mod_id=nbtcopy
mod_version=1.0.5

mod_group_id=net.mt1006.nbtcopy
mod_jar_name=NBTcopy

mod_name=NBT Copy
mod_license=LGPL-3.0-only

mod_authors=mt1006
mod_description=Adds copy button for the "/data get" command output.
mod_url=https://github.com/mt1006/mc-nbtcopy-mod
mod_issues=https://github.com/mt1006/mc-nbtcopy-mod/issues
