org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21
forge_version=51.0.26

minecraft_version_range=[1.20.5,)
forge_version_range=[50,)
loader_version_range=[50,)

mapping_channel=parchment
mapping_version=2024.07.07-1.21


## Mod Properties
mod_id=nbt_copy
mod_version=1.0.2

mod_group_id=com.mt1006.nbt_copy
mod_jar_name=NBTcopy

mod_name=NBT Copy
mod_license=LGPL-3.0-only

mod_authors=mt1006
mod_description=Adds copy button for the "/data get" command output
mod_url=https://github.com/mt1006/mc-nbtcopy-mod
mod_issues=https://github.com/mt1006/mc-nbtcopy-mod/issues