# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# https://fabricmc.net/develop
	minecraft_version=26.1
	loader_version=0.18.5

# Mod Properties
	mod_version=1.0.5
	maven_group=net.mt1006.nbtcopy
	archives_base_name=NBTcopy

# Dependencies
	fabric_version=0.144.3+26.1
